services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db

    environment:
      POSTGRES_USER: pankaj
      POSTGRES_PASSWORD: pankaj123
      POSTGRES_DB: edusnap

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: pankajdikale/edusnap-backend:latest

    container_name: edusnap-backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://pankaj:pankaj123@postgres:5432/edusnap

    volumes:
      - insightface_models:/root/.insightface

  frontend:
    image: pankajdikale/edusnap-frontend:v1

    container_name: edusnap-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

volumes:
  postgres_data:
  insightface_models:
