apiVersion: v1
kind: Secret
metadata:
  name: edusnap-db-secret
  namespace: edusnap
type: Opaque
stringData:
  username: pankaj
  password: pankaj123
  database: edusnap

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: edusnap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pankajdikale/edusnap-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://pankaj:pankaj123@postgres:5432/edusnap"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: edusnap
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000

